apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-my-pvc
 # namespace: default 
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: webapp-my-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
